package sistemperpustakaan;

import java.sql.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class FormLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(FormLogin.class.getName());
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    
    private java.awt.Image bgOriginal;

    public FormLogin() {
        initComponents();
        
        try {
            con = Config.configDB();
            stat = con.createStatement();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        // Load gambar asli untuk resize
        bgOriginal = new javax.swing.ImageIcon(getClass().getResource("/images/Form Login.jpg")).getImage();
        // Listener resize saat maximize
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                resizeBackground();
            }
        });
    }

    private void resizeBackground() {
        int w = getContentPane().getWidth();
        int h = getContentPane().getHeight();
        if (bgOriginal != null && w > 0 && h > 0) {
            Images.setIcon(new javax.swing.ImageIcon(
                bgOriginal.getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH)));
            jPanel1.setBounds(0, 0, w, h);
            Images.setBounds(0, 0, w, h);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Judul = new javax.swing.JLabel();
        Label_Password = new javax.swing.JLabel();
        Label_Username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        Btn_Registrasi = new javax.swing.JButton();
        Btn_Login = new javax.swing.JButton();
        Btn_Close = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Images = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Judul.setBackground(new java.awt.Color(0, 0, 255));
        Judul.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        Judul.setForeground(new java.awt.Color(255, 255, 255));
        Judul.setText("Form Login");
        getContentPane().add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        Label_Password.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Label_Password.setForeground(new java.awt.Color(153, 255, 255));
        Label_Password.setText("Password");
        getContentPane().add(Label_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        Label_Username.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Label_Username.setForeground(new java.awt.Color(153, 255, 255));
        Label_Username.setText("Username");
        getContentPane().add(Label_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 320, -1));

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 320, -1));

        Btn_Registrasi.setBackground(new java.awt.Color(102, 255, 51));
        Btn_Registrasi.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Btn_Registrasi.setText("REGISTRASI");
        Btn_Registrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RegistrasiActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Registrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, 40));

        Btn_Login.setBackground(new java.awt.Color(102, 153, 255));
        Btn_Login.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Btn_Login.setText("LOGIN");
        Btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 90, 40));

        Btn_Close.setBackground(new java.awt.Color(255, 51, 102));
        Btn_Close.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Btn_Close.setText("CLOSE");
        Btn_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 100, 40));

        jPanel1.setBackground(new java.awt.Color(102, 51, 0));

        Images.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Form Login.jpg"))); // NOI18N
        Images.setToolTipText("");
        jPanel1.add(Images);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CloseActionPerformed
        dispose();
    }//GEN-LAST:event_Btn_CloseActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void Btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LoginActionPerformed
        try {
            sql = "SELECT * FROM login WHERE username='" + txt_username.getText() +
                    "' AND password='" + txt_password.getText()
                    + "'";
            rs = stat.executeQuery(sql);

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "BERHASIL LOGIN");
                String level = rs.getString("level");
                if ("1".equals(level)) {
                    new Dashboard_Admin().setVisible(true);
                } else {
                    new Dashboard_user().setVisible(true);
                }
                this.dispose(); // Close login form
            } else {
                JOptionPane.showMessageDialog(null, "username atau password salah");
                txt_username.setText(null);
                txt_password.setText(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }//GEN-LAST:event_Btn_LoginActionPerformed

    private void Btn_RegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RegistrasiActionPerformed
        dispose();
        JOptionPane.showMessageDialog(null, "Silahkan registrasi");
                new Registrasi().setVisible(true);
    }//GEN-LAST:event_Btn_RegistrasiActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Close;
    private javax.swing.JButton Btn_Login;
    private javax.swing.JButton Btn_Registrasi;
    private javax.swing.JLabel Images;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel Label_Password;
    private javax.swing.JLabel Label_Username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
