package sistemperpustakaan;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC-1B LKS-2026
 */
public class Registrasi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registrasi.class.getName());

    /**
     * Creates new form Registrasi
     */
    private java.awt.Image bgOriginal;

    public Registrasi() {
        initComponents();
        panel_tembus.setBackground(new java.awt.Color(0, 0, 0, 150));
        // Load gambar asli untuk resize
        bgOriginal = new javax.swing.ImageIcon(getClass().getResource("/images/Form Registrasi.jpg")).getImage();
        // Listener resize saat maximize
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                resizeBackground();
            }
        });
    }

    private void resizeBackground() {
        int w = getContentPane().getWidth();
        int h = getContentPane().getHeight();
        if (bgOriginal != null && w > 0 && h > 0) {
            jLabel3.setIcon(new javax.swing.ImageIcon(
                bgOriginal.getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH)));
            jLabel3.setBounds(0, 0, w, h);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_batal = new javax.swing.JButton();
        btn_buat = new javax.swing.JButton();
        panel_tembus = new javax.swing.JPanel();
        txt_user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_batal.setBackground(new java.awt.Color(0, 255, 255));
        btn_batal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.addActionListener(this::btn_batalActionPerformed);
        getContentPane().add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 120, 30));

        btn_buat.setBackground(new java.awt.Color(0, 255, 255));
        btn_buat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_buat.setText("Buat");
        btn_buat.addActionListener(this::btn_buatActionPerformed);
        getContentPane().add(btn_buat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 120, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Password");

        txt_pass.addActionListener(this::txt_passActionPerformed);

        javax.swing.GroupLayout panel_tembusLayout = new javax.swing.GroupLayout(panel_tembus);
        panel_tembus.setLayout(panel_tembusLayout);
        panel_tembusLayout.setHorizontalGroup(
            panel_tembusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tembusLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_tembusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(panel_tembusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_user, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(txt_pass))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panel_tembusLayout.setVerticalGroup(
            panel_tembusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tembusLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_tembusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(panel_tembusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        getContentPane().add(panel_tembus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 410, 170));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Form Registrasi.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        dispose();
        new FormLogin().setVisible(true);
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_buatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buatActionPerformed
        JOptionPane.showMessageDialog(null, "Akun berhasil dibuat, Silahkan Login");
    }//GEN-LAST:event_btn_buatActionPerformed

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    // Fungsi yang bisa dipanggil untuk memproses registrasi
    // Panggil fungsi ini di event handler tombol registrasi Anda nantinya
    public void prosesRegistrasi(String username, String password) {
        try {
            Connection con = Config.configDB();
            Statement stat = con.createStatement();
            
            // Cek apakah sudah ada admin (level = 1)
            String checkAdminSql = "SELECT count(*) as total FROM login WHERE level = '1'";
            ResultSet rs = stat.executeQuery(checkAdminSql);
            
            String level = "2"; // Default adalah user biasa
            if (rs.next()) {
                if (rs.getInt("total") == 0) {
                    // Jika belum ada admin sama sekali, akun pertama yang dibuat akan menjadi admin
                    level = "1";
                }
            }
            
            String insertSql = "INSERT INTO login (username, password, level) VALUES ('" + username + "', '" + password + "', '" + level + "')";
            stat.executeUpdate(insertSql);
            
            String roleName = level.equals("1") ? "Admin" : "Pengguna Biasa";
            JOptionPane.showMessageDialog(null, "Registrasi Berhasil! Anda didaftarkan sebagai: " + roleName);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Registrasi: " + e.getMessage());
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registrasi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_buat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panel_tembus;
    private javax.swing.JTextField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
